plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
